# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('adminId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('adminAccount', models.CharField(max_length=32)),
                ('adminPassword', models.CharField(max_length=32)),
                ('createssTime', models.DateTimeField(auto_now_add=True)),
                ('power', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Amdinlog',
            fields=[
                ('logId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('admincontent', models.CharField(max_length=200)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('colorId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('colorName', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('companyName', models.CharField(max_length=50)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataType',
            fields=[
                ('dataTypeId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('dataName', models.CharField(max_length=100)),
                ('companyId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Fonts',
            fields=[
                ('fontId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('fontName', models.CharField(max_length=32)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('formatId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pictureUrl', models.CharField(max_length=100)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='FormatInformation',
            fields=[
                ('formatinformationId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('informationName', models.CharField(max_length=100)),
                ('informationMemo', models.CharField(blank=True, max_length=100, null=True)),
                ('formatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Format')),
            ],
        ),
        migrations.CreateModel(
            name='IndexPicture',
            fields=[
                ('picId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('picUrl', models.CharField(default=0, max_length=300)),
                ('picName', models.CharField(max_length=36)),
                ('linkUrl', models.CharField(blank=True, max_length=300, null=True)),
                ('picPlace', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('informationId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('informationContent', models.TextField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('informationType', models.IntegerField()),
                ('adminId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Administrator')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('materialId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('materialName', models.CharField(max_length=50)),
                ('materialPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('materialRemainder', models.IntegerField(blank=True, null=True)),
                ('sales', models.IntegerField(blank=True, null=True)),
                ('materialIntroduction', models.TextField(blank=True, null=True)),
                ('isSecommendation', models.BooleanField(default=1)),
                ('isShow', models.BooleanField(default=1)),
                ('isColor', models.BooleanField(default=0)),
                ('picture', models.CharField(blank=True, default=0, max_length=300, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('materialInfo', models.TextField(blank=True, null=True)),
                ('colorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Colors')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialandQuality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Material')),
            ],
        ),
        migrations.CreateModel(
            name='MaterialQuality',
            fields=[
                ('materialQualityId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('materialQualityName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('newsId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=1)),
                ('newsType', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('pakId', models.CharField(max_length=36, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PackagesType',
            fields=[
                ('pakTypeld', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('pakTypeName', models.CharField(max_length=36)),
                ('isShow', models.BooleanField(default=1)),
                ('pakTypePrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('pakTypeRema', models.TextField(blank=True, null=True)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParentMeterialClass',
            fields=[
                ('parentClassId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('parentName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SealClass',
            fields=[
                ('sealClassId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=20)),
                ('isfont', models.BooleanField(default=0)),
                ('isShow', models.BooleanField(default=1)),
                ('isformat', models.BooleanField(default=0)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('fontId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Fonts')),
                ('formatId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Format')),
                ('parentClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.ParentMeterialClass')),
            ],
        ),
        migrations.CreateModel(
            name='SealClassCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Company')),
                ('sealClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass')),
            ],
        ),
        migrations.CreateModel(
            name='SealClassFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('formatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Format')),
                ('sealClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass')),
            ],
        ),
        migrations.CreateModel(
            name='SealColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Colors')),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Material')),
            ],
        ),
        migrations.CreateModel(
            name='SealFont',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fontId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Fonts')),
                ('sealClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass')),
            ],
        ),
        migrations.CreateModel(
            name='SealMaterial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Material')),
                ('sealClassId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass')),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('statementId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('statementContent', models.CharField(max_length=100)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='packages',
            name='pakTypeld',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.PackagesType'),
        ),
        migrations.AddField(
            model_name='materialandquality',
            name='materialQualityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.MaterialQuality'),
        ),
        migrations.AddField(
            model_name='material',
            name='sealClassId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='sealClassId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.SealClass'),
        ),
        migrations.AddField(
            model_name='datatype',
            name='statementId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Statement'),
        ),
    ]
