# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-23 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
        ('Seal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('userDataId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('isShow', models.BooleanField(default=1)),
                ('createTime', models.DateTimeField(auto_now_add=True)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Company')),
                ('statementId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Statement')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.CharField(max_length=36)),
                ('orderDate', models.DateTimeField(auto_now_add=True)),
                ('isPaid', models.BooleanField(default=0)),
                ('isIvoice', models.BooleanField(default=0)),
                ('logistics', models.CharField(blank=True, max_length=36, null=True)),
                ('invoiceHead', models.CharField(blank=True, max_length=50, null=True)),
                ('orderRemark', models.TextField(blank=True, null=True)),
                ('invoiceDetail', models.CharField(blank=True, max_length=20, null=True)),
                ('responseMessage', models.TextField(blank=True, null=True)),
                ('expressNum', models.CharField(blank=True, max_length=50, null=True)),
                ('orderState', models.IntegerField()),
                ('payPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('changeDate', models.DateTimeField(auto_now=True)),
                ('dateIsDeal', models.BooleanField(default=0)),
                ('addId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Add')),
            ],
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('payId', models.IntegerField(primary_key=True, serialize=False)),
                ('payName', models.CharField(max_length=20)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('styleId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('stylePic', models.CharField(max_length=100)),
                ('isShow', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Trolley',
            fields=[
                ('trollerId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('orderId_id', models.CharField(blank=True, max_length=36, null=True)),
                ('number', models.IntegerField()),
                ('materialPrice', models.DecimalField(decimal_places=2, max_digits=20)),
                ('buyData', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(default=0)),
                ('isShow', models.BooleanField(default=1)),
                ('packageType', models.CharField(blank=True, max_length=36, null=True)),
                ('singleMemo', models.CharField(max_length=200)),
                ('colorId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Colors')),
                ('fontId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Seal.Fonts')),
                ('materialId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.Material')),
                ('userDataId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.Data')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User')),
            ],
        ),
        migrations.CreateModel(
            name='UploadData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upLoadUrl', models.CharField(max_length=200)),
                ('upLoadTime', models.DateTimeField(auto_now_add=True)),
                ('dataTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.DataType')),
                ('userDataId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.Data')),
            ],
        ),
        migrations.CreateModel(
            name='UserSummitInfo',
            fields=[
                ('userSummitInfoId', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('informationContent', models.TextField()),
                ('formatInformationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Seal.FormatInformation')),
                ('trollerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.Trolley')),
            ],
        ),
        migrations.AddField(
            model_name='style',
            name='trollerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.Trolley'),
        ),
        migrations.AddField(
            model_name='order',
            name='payId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ShoppingCart.Pay'),
        ),
        migrations.AddField(
            model_name='order',
            name='privilegeId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Users.Privilege'),
        ),
        migrations.AddField(
            model_name='order',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.User'),
        ),
    ]
